initial_positions:
  manipulator_joint1: 0.0
  manipulator_joint2: -0.785
  manipulator_joint3: 0.0
  manipulator_joint4: -2.356
  manipulator_joint5: 0.0
  manipulator_joint6: 1.571
  manipulator_joint7: 0.785
  manipulator_finger_joint1: 0.02