default_velocity_scaling_factor: 0.8  # Increase from 0.1 for better speed control
default_acceleration_scaling_factor: 0.8  # Increase from 0.1 for better acceleration

joint_limits:
  manipulator_joint1:
    has_position_limits: true
    min_position: -2.9671
    max_position: 2.9671
    has_velocity_limits: true
    max_velocity: 2.3925
    has_acceleration_limits: true
    max_acceleration: 5.0

  manipulator_joint2:
    has_position_limits: true
    min_position: -1.8326
    max_position: 1.8326
    has_velocity_limits: true
    max_velocity: 2.3925
    has_acceleration_limits: true
    max_acceleration: 5.0

  manipulator_joint3:
    has_position_limits: true
    min_position: -2.9671
    max_position: 2.9671
    has_velocity_limits: true
    max_velocity: 2.3925
    has_acceleration_limits: true
    max_acceleration: 5.0

  manipulator_joint4:
    has_position_limits: true
    min_position: -3.1416
    max_position: 0.088
    has_velocity_limits: true
    max_velocity: 2.3925
    has_acceleration_limits: true
    max_acceleration: 5.0

  manipulator_joint5:
    has_position_limits: true
    min_position: -2.9671
    max_position: 2.9671
    has_velocity_limits: true
    max_velocity: 2.871
    has_acceleration_limits: true
    max_acceleration: 5.5

  manipulator_joint6:
    has_position_limits: true
    min_position: -0.0873
    max_position: 3.8223
    has_velocity_limits: true
    max_velocity: 2.871
    has_acceleration_limits: true
    max_acceleration: 5.5

  manipulator_joint7:
    has_position_limits: true
    min_position: -2.9671
    max_position: 2.9671
    has_velocity_limits: true
    max_velocity: 2.871
    has_acceleration_limits: true
    max_acceleration: 5.5

  manipulator_finger_joint1:
    has_position_limits: true
    min_position: 0.0
    max_position: 0.04
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: true
    max_acceleration: 0.5

  manipulator_finger_joint2:
    has_position_limits: true
    min_position: 0.0
    max_position: 0.04
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: true
    max_acceleration: 0.5