manipulator_hand:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_attempts: 10
  kinematics_solver_search_resolution: 0.1
  kinematics_solver_timeout: 0.5

manipulator_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_attempts: 10
  kinematics_solver_search_resolution: 0.1
  kinematics_solver_timeout: 0.5

