controller_manager:
  ros__parameters:
    update_rate : 1000
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    manipulator_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    manipulator_hand_controller:
      type: position_controllers/GripperActionController

manipulator_arm_controller:
  ros__parameters:
    joints:
      - manipulator_joint1
      - manipulator_joint2
      - manipulator_joint3
      - manipulator_joint4
      - manipulator_joint5
      - manipulator_joint6
      - manipulator_joint7

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 20.0
    action_monitor_rate: 5.0
    open_loop_control: True
    allow_integration_in_goal_trajectories: True
    allow_nonzero_velocity_at_trajectory_end: True          


manipulator_hand_controller:
  ros__parameters:
    joint: "manipulator_finger_joint1"
    action_ns: gripper_cmd
    default: True

    state_publish_rate: 20.0
    action_monitor_rate: 5.0

    open_loop_control: True
    allow_integration_in_goal_trajectories: True
    allow_nonzero_velocity_at_trajectory_end: True


    