controller_manager:
  ros__parameters:
    update_rate : 1000
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    manipulator_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - manipulator_joint1
        - manipulator_joint2
        - manipulator_joint3
        - manipulator_joint4
        - manipulator_joint5
        - manipulator_joint6
        - manipulator_joint7

manipulator_arm_controller:
  ros__parameters:
    joints:
      - manipulator_joint1
      - manipulator_joint2
      - manipulator_joint3
      - manipulator_joint4
      - manipulator_joint5
      - manipulator_joint6
      - manipulator_joint7
      - manipulator_finger_joint1

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint1:
        trajectory: 0.05
        goal: 0.03